android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

kotlin.code.style=official
android.suppressUnsupportedCompileSdk=34
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process

# Taille de mémoire ajustée pour Gradle Daemon (comme les autres projets)
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8
android.suppressUnsupportedCompileSdk=34,33
